2019-12-12 15:10:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for mccree which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-12 15:10:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wxbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-12 15:10:31 ERROR (SyncWorker_0) [homeassistant.components.ios.notify] The notify.ios platform was loaded but no devices exist! Please check the documentation at https://home-assistant.io/ecosystem/ios/notifications/ for more information
2019-12-12 15:58:09 WARNING (MainThread) [homeassistant.helpers.service] Unable to find services.yaml for the mccree integration
2019-12-12 20:13:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:30.045595', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:30.045595', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:33.138230', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:33.138230', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:36.145319', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:36.145319', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:39.152167', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:39.152167', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:42.157379', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:42.157379', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:45.164324', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:45.164324', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:48.172532', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:48.172532', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:51.198006', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:51.198006', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:54.252013', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:54.252013', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:57.279662', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_received", "old_state": {"entity_id": "sensor.openwrt_router_bytes_received", "state": "22641227731", "att ... (585 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.036717+00:00", "context": {"id": "a6b9a9cfe3de447888675851247367db", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.036745', '2019-12-12 12:13:57.279662', 'a6b9a9cfe3de447888675851247367db', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:13:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:13:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:13:57.295022', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:13:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:13:57.295022', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:00.306093', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:00 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:00.306093', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:03 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:03.317468', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:03 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:03.317468', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:06 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:06.331129', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:06 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:06.331129', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:09 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:09.337677', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:09 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:09.337677', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:12 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:12.349373', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:12 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:12.349373', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:15 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:15.360217', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:15 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:15.360217', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:18 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:18.370102', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:18 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:18.370102', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:21 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:21.377334', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:21 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:21.377334', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:24 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:24.386248', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:24 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_received", "state": "1.2", "att ... (597 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037257+00:00", "context": {"id": "e1b7f2bd71e94165a0dda5c2382baf22", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037272', '2019-12-12 12:14:24.386248', 'e1b7f2bd71e94165a0dda5c2382baf22', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:24 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:14:24 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:24.391716', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:24 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:24.391716', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:27 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:27.398836', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:27 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:27.398836', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:30.408956', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:30.408956', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:33.416516', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:33.416516', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:36.425515', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:36.425515', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:39.435244', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:39.435244', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:42.439788', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:42.439788', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:45.447014', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:45.447014', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:48.455655', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:48.455655', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:51.465684', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_sent", "state": "37.2", "attrib ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.037743+00:00", "context": {"id": "f4b70657e9e84fb5ab199a1900a23166", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.037758', '2019-12-12 12:14:51.465684', 'f4b70657e9e84fb5ab199a1900a23166', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:14:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:14:51.474041', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:14:51.474041', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:14:54.483071', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:14:54.483071', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:14:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:14:57.490768', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:14:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:14:57.490768', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:00.497836', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:00 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:00.497836', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:03 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:03.504826', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:03 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:03.504826', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:06 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:06.511993', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:06 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:06.511993', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:09 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:09.519045', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:09 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:09.519045', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:12 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:12.526110', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:12 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:12.526110', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:15 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:15.532861', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:15 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:15.532861', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:18 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:18.539908', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:18 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sec_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_sec_received", "state": "8.1",  ... (611 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038219+00:00", "context": {"id": "082615a5e9ec4659824f206c32ff2c3e", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038234', '2019-12-12 12:15:18.539908', '082615a5e9ec4659824f206c32ff2c3e', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:18 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:15:18 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:18.544718', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:18 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:18.544718', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:21 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:21.551916', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:21 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:21.551916', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:24 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:24.559006', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:24 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:24.559006', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:27 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:27.566371', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:27 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:27.566371', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:30.575225', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:30.575225', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:33.582338', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:33.582338', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:36.589390', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:36.589390', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:39.596732', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:39.596732', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:42.603309', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:42.603309', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:45.610442', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "old_state": {"entity_id": "sensor.openwrt_router_kbyte_sec_sent", "state": "46.6", "attributes ... (578 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.038684+00:00", "context": {"id": "0cc98e8816e34b2fba1dd395200ff3d8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.038699', '2019-12-12 12:15:45.610442', '0cc98e8816e34b2fba1dd395200ff3d8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:15:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:45.614800', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:45.614800', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:48.622021', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:48.622021', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:51.629871', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:51.629871', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:54.637101', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:54.637101', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:15:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:57.644538', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:15:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:15:57.644538', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:00.651126', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:00 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:00.651126', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:03 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:03.657610', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:03 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:03.657610', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:06 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:06.667652', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:06 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:06.667652', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:09 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:09.675161', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:09 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:09.675161', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:12 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:12.682391', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:12 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_bytes_sent", "old_state": {"entity_id": "sensor.openwrt_router_bytes_sent", "state": "38291440273", "attributes" ... (565 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039124+00:00", "context": {"id": "be0dadfbde0842d0b6a12151b9d68b4c", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039140', '2019-12-12 12:16:12.682391', 'be0dadfbde0842d0b6a12151b9d68b4c', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:12 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:16:12 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:12.686919', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:12 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:12.686919', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:15 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:15.693984', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:15 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:15.693984', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:18 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:18.701598', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:18 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:18.701598', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:21 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:21.708785', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:21 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:21.708785', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:24 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:24.715913', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:24 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:24.715913', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:27 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:27.723057', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:27 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:27.723057', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:30 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:30.729672', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:30 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:30.729672', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:33 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:33.736378', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:33 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:33.736378', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:36 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:36.743797', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:36 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:36.743797', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:39.751808', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764329", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.039564+00:00", "context": {"id": "a5303a5b24054ef582d1f7cf378afed8", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.039581', '2019-12-12 12:16:39.751808', 'a5303a5b24054ef582d1f7cf378afed8', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:16:39 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:39.756495', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:39.756495', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:42 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:42.763598', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:42 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:42.763598', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:45 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:45.770843', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:45.770843', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:48 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:48.778024', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:48 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:48.778024', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:51 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:51.785153', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:51 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:51.785153', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:54 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:54.794508', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:54 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:54.794508', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:16:57 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:57.801880', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:16:57 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:16:57.801880', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:17:00 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:17:00.809056', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:17:00 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:17:00.809056', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:17:03 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:17:03.815605', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:17:03 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:17:03.815605', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:17:06 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:17:06.822347', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:17:06 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_sent", "old_state": {"entity_id": "sensor.openwrt_router_packets_sent", "state": "47039844", "attributes ... (573 characters truncated) ... :00", "last_updated": "2019-12-12T12:13:30.042227+00:00", "context": {"id": "51f4e6bde1de455e842e3e067a54887a", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:13:30.042247', '2019-12-12 12:17:06.822347', '51f4e6bde1de455e842e3e067a54887a', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:17:06 ERROR (Recorder) [homeassistant.components.recorder] Error in database update. Could not save after 11 tries. Giving up
2019-12-12 20:17:06 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764611", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:14:01.065555+00:00", "context": {"id": "7e8464e3c4e24dc6bda508d501932b02", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:14:01.066413', '2019-12-12 12:17:06.826896', '7e8464e3c4e24dc6bda508d501932b02', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:17:06 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764611", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:14:01.065555+00:00", "context": {"id": "7e8464e3c4e24dc6bda508d501932b02", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:14:01.066413', '2019-12-12 12:17:06.826896', '7e8464e3c4e24dc6bda508d501932b02', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:17:09 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764611", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:14:01.065555+00:00", "context": {"id": "7e8464e3c4e24dc6bda508d501932b02", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:14:01.066413', '2019-12-12 12:17:09.833854', '7e8464e3c4e24dc6bda508d501932b02', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:17:09 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764611", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:14:01.065555+00:00", "context": {"id": "7e8464e3c4e24dc6bda508d501932b02", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:14:01.066413', '2019-12-12 12:17:09.833854', '7e8464e3c4e24dc6bda508d501932b02', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
2019-12-12 20:17:12 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764611", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:14:01.065555+00:00", "context": {"id": "7e8464e3c4e24dc6bda508d501932b02", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:14:01.066413', '2019-12-12 12:17:12.841042', '7e8464e3c4e24dc6bda508d501932b02', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-12-12 20:17:12 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity: (sqlite3.OperationalError) no such table: events
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{"entity_id": "sensor.openwrt_router_packets_received", "old_state": {"entity_id": "sensor.openwrt_router_packets_received", "state": "50764611", "at ... (593 characters truncated) ... :00", "last_updated": "2019-12-12T12:14:01.065555+00:00", "context": {"id": "7e8464e3c4e24dc6bda508d501932b02", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-12-12 12:14:01.066413', '2019-12-12 12:17:12.841042', '7e8464e3c4e24dc6bda508d501932b02', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)
